import type { editor } from 'monaco-editor'

export const KVCODE_THEME = 'kvcode-dark'

const SYMBOL_KINDS = [
  'array', 'boolean', 'class', 'color', 'constant', 'constructor', 'enumerator',
  'enumeratorMember', 'event', 'field', 'file', 'folder', 'function', 'interface',
  'key', 'keyword', 'method', 'module', 'namespace', 'null', 'number', 'object',
  'operator', 'package', 'property', 'reference', 'snippet', 'string', 'struct',
  'text', 'typeParameter', 'unit', 'variable'
]

const symbolIconColors = Object.fromEntries(
  SYMBOL_KINDS.map((kind) => [`symbolIcon.${kind}Foreground`, '#b4b4b4'])
)

export const kvcodeTheme: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'c9c9c9' },
    { token: 'comment', foreground: '6b6b6b', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'f6f6f6' },
    { token: 'keyword.operator', foreground: '8f8f8f' },
    { token: 'string', foreground: '9d9d9d' },
    { token: 'string.escape', foreground: 'cbcbcb' },
    { token: 'number', foreground: 'd9d9d9' },
    { token: 'regexp', foreground: 'aeaeae' },
    { token: 'constant', foreground: 'f0f0f0' },
    { token: 'type', foreground: 'ededed' },
    { token: 'type.identifier', foreground: 'ededed' },
    { token: 'entity.name.function', foreground: 'e2e2e2' },
    { token: 'identifier', foreground: 'c2c2c2' },
    { token: 'variable', foreground: 'c2c2c2' },
    { token: 'variable.predefined', foreground: 'f0f0f0' },
    { token: 'tag', foreground: 'ededed' },
    { token: 'attribute.name', foreground: 'b4b4b4' },
    { token: 'attribute.value', foreground: '9d9d9d' },
    { token: 'delimiter', foreground: '8f8f8f' },
    { token: 'operator', foreground: '8f8f8f' },
    { token: 'namespace', foreground: 'd9d9d9' },
    { token: 'key', foreground: 'd9d9d9' },
    { token: 'metatag', foreground: 'f6f6f6' }
  ],
  colors: {
    ...symbolIconColors,
    'editor.background': '#00000000',
    'editor.foreground': '#c9c9c9',
    'editorCursor.foreground': '#f4f4f4',
    'editorLineNumber.foreground': '#4f4f4f',
    'editorLineNumber.activeForeground': '#a6a6a6',
    'editor.lineHighlightBackground': '#ffffff06',
    'editor.lineHighlightBorder': '#00000000',
    'editor.selectionBackground': '#ffffff2b',
    'editor.inactiveSelectionBackground': '#ffffff14',
    'editor.selectionHighlightBackground': '#ffffff14',
    'editor.wordHighlightBackground': '#ffffff14',
    'editor.wordHighlightStrongBackground': '#ffffff1f',
    'editor.findMatchBackground': '#ffffff38',
    'editor.findMatchHighlightBackground': '#ffffff1f',
    'editorIndentGuide.background1': '#ffffff0d',
    'editorIndentGuide.activeBackground1': '#ffffff26',
    'editorBracketHighlight.foreground1': '#c9c9c9',
    'editorBracketHighlight.foreground2': '#c9c9c9',
    'editorBracketHighlight.foreground3': '#c9c9c9',
    'editorBracketHighlight.foreground4': '#c9c9c9',
    'editorBracketHighlight.foreground5': '#c9c9c9',
    'editorBracketHighlight.foreground6': '#c9c9c9',
    'editorBracketHighlight.unexpectedBracket.foreground': '#e8e8e8',
    'editorBracketMatch.background': '#ffffff14',
    'editorBracketMatch.border': '#ffffff4d',
    'editorWhitespace.foreground': '#ffffff14',
    'editorGutter.background': '#00000000',
    'editorOverviewRuler.border': '#00000000',
    'scrollbar.shadow': '#00000000',
    'scrollbarSlider.background': '#ffffff14',
    'scrollbarSlider.hoverBackground': '#ffffff24',
    'scrollbarSlider.activeBackground': '#ffffff33',
    'editorWidget.background': '#242424f2',
    'editorWidget.border': '#ffffff1f',
    'editorSuggestWidget.background': '#242424f7',
    'editorSuggestWidget.border': '#ffffff1f',
    'editorSuggestWidget.selectedBackground': '#ffffff14',
    'editorSuggestWidget.foreground': '#c9c9c9',
    'editorSuggestWidget.selectedForeground': '#f6f6f6',
    'editorSuggestWidget.highlightForeground': '#f6f6f6',
    'editorSuggestWidget.focusHighlightForeground': '#f6f6f6',
    'editorSuggestWidgetStatus.foreground': '#8f8f8f',
    'editorWidget.foreground': '#c9c9c9',
    'editorHoverWidget.foreground': '#c9c9c9',
    'descriptionForeground': '#8f8f8f',
    'textLink.foreground': '#ededed',
    'textLink.activeForeground': '#f6f6f6',
    'editorLink.activeForeground': '#f6f6f6',
    'list.highlightForeground': '#f6f6f6',
    'list.focusHighlightForeground': '#f6f6f6',
    'list.hoverBackground': '#ffffff0d',
    'list.focusBackground': '#ffffff14',
    'list.focusForeground': '#f6f6f6',
    'list.activeSelectionBackground': '#ffffff14',
    'list.activeSelectionForeground': '#f6f6f6',
    'list.inactiveSelectionBackground': '#ffffff0d',
    'progressBar.background': '#b2b2b2',
    'editorHoverWidget.background': '#242424f7',
    'editorHoverWidget.border': '#ffffff1f',
    'input.background': '#2b2b2b',
    'input.border': '#ffffff1f',
    'focusBorder': '#ffffff4d',
    'editorError.foreground': '#e8e8e8',
    'editorWarning.foreground': '#b4b4b4',
    'editorInfo.foreground': '#8f8f8f'
  }
}
